export enum FIELDS {
    NAME = 'name',
    SLUG = 'slug',
    DESCRIPTION = 'description',
    CATEGORIES = 'categories',
    CATEGORY = 'category',
    SUBCATEGORIES = 'subcategories',
    SUBCATEGORY = 'subcategory',
    AUTHOR = 'author',
    USER = 'user',
    ID = 'id',
    CREATED_AT = 'createdAt',
    SIZE = 'size',
    COMPLETED = 'completed',
    LANGUAGES = 'languages',
}